# Generated by Django 3.1.6 on 2021-08-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileClient', '0003_profile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
    ]
